# Generated by Django 4.1.4 on 2022-12-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brend', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100)),
                ('WorkExperience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100)),
                ('work_experience', models.IntegerField()),
                ('chief', models.ForeignKey(db_column='ChiefID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.chief')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stock', models.CharField(max_length=50)),
                ('start_stock', models.CharField(max_length=50)),
                ('finish_stock', models.CharField(max_length=50)),
                ('persent_stock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=100)),
                ('chief', models.ForeignKey(db_column='ChiefID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.chief')),
                ('guard', models.ForeignKey(db_column='GuardID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.guard')),
                ('post', models.ForeignKey(db_column='PostID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.post')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=50)),
                ('catagory', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.brend')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.stock')),
            ],
        ),
        migrations.CreateModel(
            name='OnDuty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exit_time', models.DateTimeField()),
                ('chief', models.ForeignKey(db_column='ChiefID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.chief')),
                ('guard', models.ForeignKey(db_column='GuardID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.guard')),
                ('post', models.ForeignKey(db_column='PostID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.post')),
            ],
        ),
    ]
