# Generated by Django 4.1.4 on 2022-12-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('ChiefID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=100)),
                ('WorkExperience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('GuardID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=100)),
                ('WorkExperience', models.IntegerField()),
                ('ChiefID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.chief')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('RemarkID', models.IntegerField(primary_key=True, serialize=False)),
                ('Remark', models.CharField(max_length=100)),
                ('ChiefID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.chief')),
                ('GuardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.guard')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.post')),
            ],
        ),
        migrations.CreateModel(
            name='OnDuty',
            fields=[
                ('OnDutyID', models.IntegerField(primary_key=True, serialize=False)),
                ('ExitTime', models.DateTimeField()),
                ('ChiefID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.chief')),
                ('GuardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.guard')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.post')),
            ],
        ),
    ]
