# Generated by Django 4.1.4 on 2022-12-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chief',
            old_name='WorkExperience',
            new_name='work_experience',
        ),
    ]
