# Generated by Django 4.1.4 on 2022-12-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_chief_guard_post_remark_onduty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='ChiefID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guard',
            name='ChiefID',
            field=models.ForeignKey(db_column='ChiefID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.chief'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='ChiefID',
            field=models.ForeignKey(db_column='ChiefID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.chief'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='GuardID',
            field=models.ForeignKey(db_column='GuardID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.guard'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='PostID',
            field=models.ForeignKey(db_column='PostID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.post'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='ChiefID',
            field=models.ForeignKey(db_column='ChiefID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.chief'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='GuardID',
            field=models.ForeignKey(db_column='GuardID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.guard'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='PostID',
            field=models.ForeignKey(db_column='PostID', on_delete=django.db.models.deletion.DO_NOTHING, to='hello.post'),
        ),
    ]
